//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TattooDBEntities : DbContext
    {
        private static TattooDBEntities content; 
        public TattooDBEntities()
            : base("name=TattooDBEntities")
        {
        }

        public static TattooDBEntities GetContent()
        {
            if (content == null)
                content = new TattooDBEntities();
            return content;
        }

        public static TattooDBEntities Reload()
        {
            content = new TattooDBEntities();
            return content;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Element> Element { get; set; }
        public virtual DbSet<Ink> Ink { get; set; }
        public virtual DbSet<InkType> InkType { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Style> Style { get; set; }
        public virtual DbSet<Tattoo> Tattoo { get; set; }
    }
}
